# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # - name: My first step
      #  if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
      #  run: echo ${{ github.event_name}} This event is a pull request that had an assignee removed.
   
      - name: Running CI
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: "http://0149a44cdda1.ngrok.io/api/webhooks/sources/github/triggers/build"
          data: '{"value": "${{ github.event.action }}"}'
